name: bmadx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipython
  - ipykernel
  - numpy
  - matplotlib
  - pytest
  - numba
  - numdifftools
  - kornia
  - bmad
  - pytao
  - distgen
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
